# application configuration
micronaut:
  application:
    name: baseline-micronaut

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

  server:
    # let system environment variable override context-path if available
    # or else just use / as root. The Dockerfile sets this to /otc matching
    # what the ECS Fargate task is routed as from the load balancer.
    context-path: ${CONTEXT_PATH:/}
    port: 8080
    cors:
      enabled: false

  security:
    enabled: true
    endpoints:
      login:
        enabled: true

endpoints:
  health:
    enabled: false
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
  json-view:
    enabled: true

flyway:
  datasources:
    default:
      locations: classpath:dbmigrations
      out-of-order: false

datasources:
  default:
    url: 'jdbc:h2:mem:flywayDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
